version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - APP_ENV_PATH=/env/.env
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app:cached
      - ./.env:/env/.env:ro
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
