services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - APP_ENV_PATH=/env/.env
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app:cached
      - ./.env:/env/.env:ro
      - node_modules:/usr/src/app/node_modules
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: {}
  node_modules: {}
